server:
  port: 8081
spring:
  profiles:
    active: myqa

---
spring:
  config:
    activate:
      on-profile: myqa
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: prasanna
    password: HiWorld@2024
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 100
      minimum-idle: 50
      max-lifetime: 600000
      idle-timeout: 550000
    tomcat:
      max-active: 50
      initial-size: 20
      min-idle: 8
      max-idle: 25
      max-wait: 20000
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        default_schema: employee
        generate_statistics: true
        format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect



